apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gke
images:
  - name: us-west1-docker.pkg.dev/iz27-platform-dev/symphony/controller
    newName: us-west1-docker.pkg.dev/iz27-platform-dev/symphony/controller
    digest: sha256:e16d8b7a463b6735dea00581d433e0b823391fc6d43846b628743958d80b8bb0
commonAnnotations:
  symphony.openai.com/source-revision: f957b7b3d3e4aa6792687f8c31abe1467e36de7f
